build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8
    ignoreDefaultParameters: true
    ignoreAnnotated:
      - "Composable"
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  TooManyFunctions:
    active: true
    thresholdInFiles: 15
    thresholdInClasses: 15
    thresholdInInterfaces: 15
    thresholdInObjects: 15
    thresholdInEnums: 15

coroutines:
  active: true

empty-blocks:
  active: true

exceptions:
  active: true

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - "Composable"
  TopLevelPropertyNaming:
    active: true
    constantPattern: "[A-Z][A-Za-z0-9]*"

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludeCommentStatements: true
  WildcardImport:
    active: false
  MagicNumber:
    active: true
    excludes:
      - "**/test/**"
      - "**/androidTest/**"
      - "**/*Test.kt"
      - "**/*Spec.kt"
  ReturnCount:
    active: true
    max: 3
    excludeGuardClauses: true
  ForbiddenComment:
    active: false
